### PR TITLE
Add typescript declaration file.

### PR DESCRIPTION
**Pull request by lightrabbit**

### CODE REVIEW

**Comment by Philmod** [comment]
Hey @lightrabbit, could you tell me how does that work? Maybe a link so I can understand?
Does this need any test?

**Comment by lightrabbit** [comment]
http://www.typescriptlang.org/docs/handbook/module-resolution.html
http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

When a TypeScript project needs to use a package written in pure Javascrpit. This package requires a related declaration file to provide the TypeScript compiler with valid type information. Otherwise, developers need to write their own declaration files about this package in the project.
In this pull request, I wrote a declaration file for this package. When other TypeScript developers use this package, there is no need to write additional declaration files for this package.

I don't think it is necessary to write tests for this declaration file. Because this package has only one class, and its properties are not many. You can see directly from the code whether the declaration file is written incorrectly.
If you really need to write a test, you only need to rewrite the current test with TypeScript. Then use the TypeScript compiler to compile it to see if it can be compiled successfully.

**Comment by Philmod** [comment]
Ok, thanks

**Comment by lightrabbit** [comment]
Can you publish the latest version to NPM? Thanks.

**Comment by Philmod** [comment]
Done

**Pull request merged**
