### PR TITLE
Adds an option to keep only a given number of intergral terms

### PR DESCRIPTION
**Pull request by emersion**
Useful when target changes frequently.

Adds an option `sumLength`.

### CODE REVIEW

**Comment by Philmod** [comment]
1. Could you tell me some use cases in which you want to limit the number of integral terms?
2. Should the parameter be set up in the constructor (next to the others parameters)?
3. What do you think of a default value of `-1` for infinite `sumLength`?

**Comment by emersion** [comment]
1. The purpose is to prevent [integral windup](https://en.wikipedia.org/wiki/PID_controller#Integral_windup). But it seems that adding instead a `i_max` parameter would have the same effect. Maybe it is better and simpler to do that?
2. Since most people won't use it, I though it was better not to add it as param, to avoid having a long list of parameters. Maybe we should support an options object?
3. I'll change that :-P

**Comment by luzlab** [comment]
Hi - I'd really like to use this pull request. We're having a lot of problems with integral windup, and I'd prefer to use your package rather than making a new fork. Also, max and min parameters might be enough to solve my problems.

**Comment by Philmod** [comment]
@emersion Yes, I think an option object with more parameters makes sense, so the user doesn't have to modify the class.
Another option would be to have a setter method.

**Pull request closed without merging**
